default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: '<%= ENV['DATABASE_USERNAME'] %>'
  password: '<%= ENV['DATABASE_PASSWORD'] %>'

development:
  <<: *default
  database: LoomLuxe_development

test:
  <<: *default
  database: LoomLuxe_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
